x function

diff --git a/husky b/husky
--- a/husky
+++ b/husky
@@ -9,12 +9,23 @@ for f in "${XDG_CONFIG_HOME:-$HOME/.config}/husky/init.sh" "$HOME/.huskyrc"; do
 	# shellcheck disable=SC1090
 	[ -f "$f" ] && . "$f"
 done
-
 [ "${HUSKY-}" = "0" ] && exit 0
 
-sh -e "$s" "$@"
-c=$?
+f=$([ "$h" = "pre-commit" ] && git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
+x() {
+	[ -z "$f" ] && return
+	g=$(echo "$f" | grep "$1")
+	echo "$g" | xargs "$2"
+	echo "$g" | xargs git add
+}
 
-[ $c != 0 ] && echo "husky - $h script failed (code $c)"
-[ $c = 127 ] && echo "husky - command not found in PATH=$PATH"
-exit $c
+h() {
+	[ $c != 0 ] && echo "husky - $h script failed (code $c)"
+	[ $c = 127 ] && echo "husky - command not found in PATH=$PATH"
+	exit 1
+}
+
+trap 'c=$?; h' EXIT
+
+set -e
+. "$s"
